
# This is the Supabase config file.

# Note: The project_id is randomly generated and unique to your project.
# Changing this value might result in data loss.
project_id = "ihvgtaxvrqdnrgdddhdx"

# You can update the name to your project/product name.
name = "Assignment-Hub"

[api]
port = 9000
schemas = ["public", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 5432
major_version = 15

[studio]
port = 9100

[inbucket]
port = 9200

[auth]
site_url = "https://www.assignmenthub.org"
additional_redirect_urls = ["http://localhost:3000", "https://localhost:3000", "https://www.assignmenthub.org"]
jwt_expiry = 3600
enable_signup = true

[storage]
file_size_limit = "50MiB"

[storage.buckets]
avatars = { public = true }
